const EARTH_RADIUS_METERS = 6371000;

function normalizeStreetName(value = "") {
  return String(value)
    .toUpperCase()
    .replace(/\bWEST\b/g, "W")
    .replace(/\bEAST\b/g, "E")
    .replace(/\bNORTH\b/g, "N")
    .replace(/\bSOUTH\b/g, "S")
    .replace(/\bSTREET\b/g, "ST")
    .replace(/\bAVENUE\b/g, "AVE")
    .replace(/\bBOULEVARD\b/g, "BLVD")
    .replace(/\bPLACE\b/g, "PL")
    .replace(/\bCOURT\b/g, "CT")
    .replace(/\bCIRCLE\b/g, "CIR")
    .replace(/\bROAD\b/g, "RD")
    .replace(/\bDRIVE\b/g, "DR")
    // Denver calls this roadway S Irving St while the public-road inventory
    // calls the same divided carriageway South Irving Street Parkway.
    .replace(/\bIRVING ST PARKWAY\b/g, "IRVING ST")
    .replace(/[^A-Z0-9]+/g, " ")
    .trim()
    .replace(/^[NSEW] /, "");
}

function distanceMeters(a, b) {
  const lat1 = a[0] * Math.PI / 180;
  const lat2 = b[0] * Math.PI / 180;
  const dLat = lat2 - lat1;
  const dLon = (b[1] - a[1]) * Math.PI / 180;
  const h = Math.sin(dLat / 2) ** 2 + Math.cos(lat1) * Math.cos(lat2) * Math.sin(dLon / 2) ** 2;
  return 2 * EARTH_RADIUS_METERS * Math.asin(Math.sqrt(h));
}

function distanceToSegmentMeters(point, start, end) {
  const meanLat = ((point[0] + start[0] + end[0]) / 3) * Math.PI / 180;
  const scaleX = Math.cos(meanLat) * Math.PI * EARTH_RADIUS_METERS / 180;
  const scaleY = Math.PI * EARTH_RADIUS_METERS / 180;
  const px = point[1] * scaleX;
  const py = point[0] * scaleY;
  const ax = start[1] * scaleX;
  const ay = start[0] * scaleY;
  const bx = end[1] * scaleX;
  const by = end[0] * scaleY;
  const dx = bx - ax;
  const dy = by - ay;
  const denominator = dx * dx + dy * dy;
  const t = denominator ? Math.max(0, Math.min(1, ((px - ax) * dx + (py - ay) * dy) / denominator)) : 0;
  return Math.hypot(px - (ax + t * dx), py - (ay + t * dy));
}

function distanceToPathMeters(point, path) {
  if (!Array.isArray(path) || path.length < 2) return Infinity;
  let minimum = Infinity;
  for (let index = 1; index < path.length; index += 1) {
    minimum = Math.min(minimum, distanceToSegmentMeters(point, path[index - 1], path[index]));
  }
  return minimum;
}

function samplePath(path, spacingMeters = 8) {
  const samples = [path[0]];
  for (let index = 1; index < path.length; index += 1) {
    const start = path[index - 1];
    const end = path[index];
    const steps = Math.max(1, Math.ceil(distanceMeters(start, end) / spacingMeters));
    for (let step = 1; step <= steps; step += 1) {
      const ratio = step / steps;
      samples.push([
        start[0] + (end[0] - start[0]) * ratio,
        start[1] + (end[1] - start[1]) * ratio
      ]);
    }
  }
  return samples;
}

function routeHasUsableSchedule(route) {
  return !route.dataUnavailable && Boolean(
    route.leftSweepingRule || route.rightSweepingRule || (Array.isArray(route.schedules) && route.schedules.length)
  );
}

function makeUnavailableRoute(block) {
  const path = block.geometry;
  return {
    id: `unavailable-${block.id}`,
    streetName: block.streetName,
    from: block.from,
    to: block.to,
    sweepType: "Unavailable",
    leftSweepDirection: "Left",
    rightSweepDirection: "Right",
    leftSweepingRule: "Denver route data unavailable — check posted signs.",
    rightSweepingRule: "Denver route data unavailable — check posted signs.",
    schedules: [],
    isPosted: false,
    dataUnavailable: true,
    expectedBlockId: block.id,
    map: { staticMapUrl: "", center: path[Math.floor(path.length / 2)], path },
    sourceNote: "Generated by the inventory auditor because a public roadway exists here but Denver returned no usable schedule."
  };
}

function auditInventory({ routes, blocks, matchToleranceMeters = 12, minimumCoverage = 0.9, generateUnavailable = true }) {
  const routeList = Array.from(routes.values ? routes.values() : routes);
  const generatedRoutes = [];
  const blockResults = [];

  for (const block of blocks) {
    if (block.excluded) {
      blockResults.push({ id: block.id, streetName: block.streetName, status: "excluded", reason: block.exclusionReason || "excluded by area manifest" });
      continue;
    }
    if (!block.id || !block.streetName || !Array.isArray(block.geometry) || block.geometry.length < 2) {
      blockResults.push({ id: block.id || null, streetName: block.streetName || null, status: "unexplained-gap", reason: "invalid expected-block definition" });
      continue;
    }

    const streetKey = normalizeStreetName(block.streetName);
    const candidates = routeList.filter((route) => normalizeStreetName(route.streetName) === streetKey && Array.isArray(route.map?.path));
    const scheduled = candidates.filter(routeHasUsableSchedule);
    const samples = samplePath(block.geometry);
    const coveredSamples = samples.filter((point) => scheduled.some((route) => distanceToPathMeters(point, route.map.path) <= matchToleranceMeters));
    const coverage = coveredSamples.length / samples.length;

    if (coverage >= minimumCoverage) {
      blockResults.push({ id: block.id, streetName: block.streetName, from: block.from, to: block.to, status: "scheduled", coverage, routeIds: scheduled.map((route) => route.id) });
      continue;
    }

    const existingUnavailable = candidates.find((route) => route.dataUnavailable && (
      route.expectedBlockId === block.id || samplePath(block.geometry).every((point) => distanceToPathMeters(point, route.map.path) <= matchToleranceMeters)
    ));
    if (existingUnavailable) {
      blockResults.push({ id: block.id, streetName: block.streetName, from: block.from, to: block.to, status: "unavailable", coverage, routeIds: [existingUnavailable.id] });
    } else if (generateUnavailable) {
      const unavailable = makeUnavailableRoute(block);
      generatedRoutes.push(unavailable);
      routeList.push(unavailable);
      blockResults.push({ id: block.id, streetName: block.streetName, from: block.from, to: block.to, status: "unavailable", coverage, routeIds: [unavailable.id], generated: true });
    } else {
      blockResults.push({ id: block.id, streetName: block.streetName, from: block.from, to: block.to, status: "unexplained-gap", coverage });
    }
  }

  const counts = blockResults.reduce((result, block) => {
    result[block.status] = (result[block.status] || 0) + 1;
    return result;
  }, { expected: blockResults.filter((block) => block.status !== "excluded").length, scheduled: 0, unavailable: 0, excluded: 0, "unexplained-gap": 0 });

  return {
    generatedRoutes,
    report: { version: 1, counts, blocks: blockResults },
    unexplainedGaps: blockResults.filter((block) => block.status === "unexplained-gap")
  };
}

module.exports = { auditInventory, makeUnavailableRoute, normalizeStreetName, routeHasUsableSchedule };
